//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatingCRUDApplicationWithImages.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class EmpTable
    {
        public int id { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Name is required !")]
        public string name { get; set; }

        [DisplayName("Employee Desiganation")]
        [Required(ErrorMessage = "Desiganation is required !")]
        public string desiganation { get; set; }

        [DisplayName("Employee Image")]
        public string imagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
