//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowToUpdateEntityDataModelUsingEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class StudentTable
    {
        public int id { get; set; }

        [DisplayName("Name")]
        public string name { get; set; }

        [DisplayName("Standard")]
        public int standard { get; set; }

        [DisplayName("Age")]
        public int age { get; set; }
    }
}
