//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatingSignUpORRegisterPageWithLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is a required !")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last name is a required !")]
        public string lastName { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is a required !")]
        public string gender { get; set; }

        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is a required !")]
        public int age { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is a required !")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invalid Email")]
        public string email { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is a required !")]
        public string username { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is a required !")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm password is a required !")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage ="Password is not same !")]
        public string confirmPassword { get; set; }
    }
}
